#! /bin/tcsh -f
#This code makes an ensemble of CLM site instances. 

setenv CODENAME clm5.0_apr26/
setenv NAME FACE_ENSEMBLE_TRANSIENT_
set Ha1=6
set niter=5
set nparam=15
set p=1
set nsites=8
set BASEBUILD=CLM5_SPR_SPIN_HL_.1x1pt_US-Ha1
set BASEYEAR=201
set PARAMROOT='/glade/p/work/rfisher/git/CLM5_FACE_EXPTS/matlab/FACE_pftfiles/FACE_CLM_params_may1_highleaf_pi'
set RESTARTCASES=('CLM5_SPR_SPIN_.1x1pt_Br-cax' 'CLM5_SPR_SPIN_.bci_0.1x0.1_v4.0i'  'CLM5_SPR_SPIN_HL_.1x1pt_US-ORN' 'CLM5_SPR_SPIN_HL_.1x1pt_US-Brw'  'CLM5_SPR_SPIN_HL_.1x1pt_US-NR1'  'CLM5_SPR_SPIN_HL_.1x1pt_US-Ha1'  'CLM5_SPR_SPIN_HL_.1x1pt_US-Me2')
set SITENAMES=('1x1pt_Br-cax' 'bci_0.1x0.1_v4.0i' '1x1pt_US-ORN' '1x1pt_US-Brw' '1x1pt_US-NR1' '1x1pt_US_Ha1' '1x1pt_US-Me2')
set SITENAMES_NEW=('CAX' 'BCI' 'ORN' 'BRW' 'NWR' 'HAF' 'MET')
set casesdir = CLM5_POINTSIMS
set co2streams='/glade/p/work/rfisher/git/CLM5_FACE_EXPTS/case_scripts/co2_files/user_datm.streams.txt.co2tseries.allyear.20tr'

set s=1
while ($s<$nsites)
       set BASECASE=CLM5_$SITENAMES[$s]_ens_PI00 
  
       setenv EXPTNAME CLM5_$SITENAMES[$s]_ens_transient_ELEV_PI00
       cd  /glade/p/work/rfisher/git/$CODENAME
       cd cime/scripts
       cd $casesdir
       rm -rf $EXPTNAME
       rm -rf /glade/scratch/rfisher/$EXPTNAME
       pwd
       ../create_clone --clone $BASECASE --case $EXPTNAME

       cd $EXPTNAME

       ./xmlchange STOP_N=80
       ./xmlchange STOP_OPTION=nyears
       ./xmlchange RESUBMIT=3
       ./xmlchange CCSM_CO2_PPMV=287
       ./xmlchange EXEROOT="/glade/scratch/rfisher/$BASEBUILD/bld/"
       ./xmlchange BUILD_COMPLETE="TRUE"
       ./xmlchange JOB_WALLCLOCK_TIME=05:45:00
       ./xmlchange RUN_STARTDATE=1850-01-01
       ./xmlchange CLM_CO2_TYPE=diagnostic
       ./xmlchange PROJECT=P93300041
       ./xmlchange DATM_CO2_TSERIES=20tr
       ./xmlchange CCSM_BGC=CO2A
       ./xmlchange CONTINUE_RUN="FALSE"

       #./xmlchange JOB_QUEUE=share
       #./xmlchange MAX_TASKS_PER_NODE=1
       #./xmlchange MPILIB=mpi-serial

      # set uclm="fsurdat='/glade/u/home/rfisher/single_point_drivers/$SITENAMES[$s]/surfdata_$SITENAMES[$s].nc'\nfinidat='/glade/scratch/rfisher/archive/$BASECASE/rest/0$BASEYEAR-01-01-00000/$BASECASE.clm2.r.0$BASEYEAR-01-01-00000.nc'"


        if( $s == $Ha1 )then
          set site='1x1pt_US-Ha1'
        else
         set site=$SITENAMES[$s]
        endif

      set uclm="fsurdat='/glade/p/work/rfisher/git/CLM5_FACE_EXPTS/case_scripts/sitefiles/$site/surfdata_$site.nc'\nfinidat='/glade/scratch/rfisher/archive/$BASECASE/rest/0$BASEYEAR-01-01-00000/$BASECASE.clm2.r.0$BASEYEAR-01-01-00000.nc'\nparamfile='/glade/p/work/rfisher/git/CLM5_FACE_EXPTS/matlab/FACE_pftfiles/FACE_CLM_params_may1_highleaf_pi00.nc'"

      echo  $uclm >user_nl_clm
      echo $uclm

      cp /glade/p/work/rfisher/git/CLM5_FACE_EXPTS/case_scripts/co2_files/user_nl_datm_FACE_transient_ELEV_$site user_nl_datm
      cp $co2streams user_datm.streams.txt.co2tseries.20tr
       ./case.setup

       #./case.build
       ./case.submit

       
echo $EXPTNAME
@ s ++
end

    
