#! /bin/tcsh -f
#This code makes an ensemble of CLM site instances. 

setenv CODENAME clm5.0_apr26/
setenv NAME FACE_ENSEMBLE_
set niter=5
set nparam=3
set nsites=4
set BASEBUILD=CLM5_SPR_SPIN_HL_.1x1pt_US-ORN
set BASEYEAR=201
set PARAMROOT='/glade/p/work/rfisher/git/CLM5_FACE_EXPTS/matlab/FACE_pftfiles/FACE_CLM_params_may1_highleaf_pi'
set BASECASES=('CLM5_1x1pt_Br-cax_ens_transient_PI00' 'CLM5_bci_0.1x0.1_v4.0i_ens_transient_PI00' 'CLM5_1x1pt_US-ORN_ens_transient_PI00')
set SITENAMES=('1x1pt_Br-cax' 'bci_0.1x0.1_v4.0i' '1x1pt_US-ORN')
set POINTDIR=CLM5_POINTSIMS
#set co2streams='/glade/p/work/rfisher/git/CLM5_FACE_EXPTS/case_scripts/co2_files/user_datm.streams.txt.co2tseries.allyear.20tr'

set s=3
while ($s<$nsites)
  set BASECASE=$BASECASES[$s]
  
  set p=2
  while ($p<$nparam)

    set x=1
    while ($x<$niter)

       setenv EXPTNAME CLM5_$SITENAMES[$s]_ens_transient_NDEP_PI$p$x
       cd  /glade/p/work/rfisher/git/$CODENAME
       pwd
       cd cime/scripts/
       cd ${POINTDIR}
       pwd

       cd $EXPTNAME
       pwd
       ./xmlchange STOP_N=80
       ./xmlchange RESUBMIT=2
       ./xmlchange JOB_WALLCLOCK_TIME=05:45:00
       ./xmlchange CONTINUE_RUN="TRUE"

       ./case.submit
       @ x ++
       end
   @ p ++
   end
@ s ++
end

    
